### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by LXQtBot**
Translations update from [Weblate](https://translate.lxqt-project.org/projects/redtide/sddm-conf/) for redtide/SDDM-conf.

### CODE REVIEW

**Comment by stefonarch** [comment]
I hope it's ok that I merge those (including cleanup of the commit message).

**Comment by redtide** [comment]
Yes, I just wait for a while for more changes to make less merges.
I'm not sure what you mean with "cleanup of the commit message".

**Comment by stefonarch** [comment]
> I'm not sure what you mean with "cleanup of the commit message".

They have double entries, no idea where those come from, example:
```
Co-authored-by: Bashishtha Narayan Singh <bashishtha.singh@gmail.com>
Co-authored-by: Dimitrios Glentadakis <dglent@free.fr>
Co-authored-by: Weblate <noreply@weblate.org>
Translate-URL: https://translate.lxqt-project.org/projects/lxqt-configuration/lxqt-config-appearance/hi/
Translate-URL: https://translate.lxqt-project.org/projects/lxqt-configuration/lxqt-config-locale/hi/
Translation: LXQt Configuration/lxqt-config-appearance
Translation: LXQt Configuration/lxqt-config-locale

Co-authored-by: Weblate <noreply@weblate.org>
Co-authored-by: Bashishtha Narayan Singh <bashishtha.singh@gmail.com>
Co-authored-by: Dimitrios Glentadakis <dglent@free.fr>
```
I remove also the weblate line usually.

**Comment by redtide** [comment]
I don't see double entries but only multiple ones of the same type (they just looks a bit redundant to me, not duplicates)

**Comment by stefonarch** [comment]
I meant those.

**Comment by redtide** [comment]
IDK how I haven't noticed the "co authored" ones; no Weblate settings to adjust git commit messages?

**Comment by stefonarch** [comment]
It's also the Bot, I didn't figure it out. 
In weblate there are settings but the only thing possible is oppress those lines all. But it's not a big issue.

**Pull request merged**
