### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by LXQtBot**
Translations update from [Weblate](https://translate.lxqt-project.org/projects/redtide/sddm-conf/) for redtide/SDDM-conf.

### CODE REVIEW

**Comment by stefonarch** [comment]
He's so fast always :)  but I think this can  be closed. Merge https://github.com/redtide/sddm-conf/pull/7 instead

**Comment by redtide** [comment]
I was about checking it, there are also some corrections on translations other than the "unfinished" removal

**Comment by redtide** [comment]
though I'm not sure if it was mergeable once solved the conflicts

**Comment by stefonarch** [comment]
Maybe just make a PR with his file now is the easiest way. I added it in weblate and closed it, but he got the email and was faster...

**Pull request closed without merging**
