### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by LXQtBot**
Translations update from [Weblate](https://translate.lxqt-project.org/projects/redtide/sddm-conf/) for redtide/SDDM-conf.

### CODE REVIEW

**Comment by redtide** [comment]
I see some people is injecting their info in the about dialog instead of translate the string as is.
I think to add in future a "Translators" page on it but until then I don't want this kind of tricks, so I'm not going to merge any pull request from now on with this behavior.
@stefonarch what is the action taken usually in these case? Should I close the PR or wait for some change?

**Comment by tsujan** [comment]
The same thing was done by @MarongHappy at https://github.com/tsujan/Kvantum/pull/823. I closed it.

Unfortunately, here the correct and incorrect translations are inside the same PR.

**Comment by stefonarch** [comment]
Closing should work, but translations are lost. Contacting  the author first and then merging and remove (probably better in weblate) the info?

**Comment by redtide** [comment]
> Contacting the author first and then merging and remove (probably better in weblate) the info?

Yes, though it could be better if there were some kind of "broadcast messaging/chat" to tell people to not do it (at this point for any application in weblate, not only mine)

**Comment by redtide** [comment]
It seems I gave a too quick look to these recent changes, the Korean translation is the only one with that issue, and now I notice that also PicomConf has the same but was merged.
Thank you for the help and suggestions! I'm still a bit lost in this Weblate thing.

**Comment by stefonarch** [comment]
Hm, I think I've overseen some: https://github.com/lxqt/pcmanfm-qt/pull/1663/files

**Comment by stefonarch** [comment]
> I don't think so;

Yes, you're right. I'll contact him and ask him to revert those changes. 
Thinking more about it it's not really a bad place for translators info:  only the few for the given language will be shown.

**Pull request merged**
